---
Name: SilverStripe Algolia page sync module
---
Page:
  Extensions:
    - AlgoliaSyncModuleDirectLease\PageAlgoliaExtension
AlgoliaSyncFieldslocalised:
AlgoliaSyncFieldsNonlocalised:
AlgoliaSyncImageslocalised:
AlgoliaSyncImagessNonlocalised:
